# Generated by Django 4.1 on 2022-08-05 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateField(blank=True, default=datetime.datetime.now)),
                ('daily', models.BooleanField(default=False)),
                ('weekly', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
            ],
        ),
    ]
