# Generated by Django 4.1 on 2022-08-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
